

name:  deployToScratchOrg
# Controls when the workflow will run
on:
  # Triggers the workflow on pull request events but only for the main branch
  workflow_dispatch:
  
  pull_request:
    branches: 
      - main
      - 'feature/*'
      - 'bugfix/*'
  

  # Allows you to run this workflow manually from the Actions tab

# A workflow run is made up of one or more jobs that can run sequentially or in parallel

jobs:
  deploy-org:
    container : salesforce/salesforcedx:latest-full
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
          env:
            DEV_HUB_URL: force://PlatformCLI::5Aep861mdLLi91HqFe_H9mH_jIScAOIOk6c0pLcjrIyKBY98Dcn8b7A9w8gvRnSh1POOBNZsape0HOFcmaBBr4k@deloitte486-dev-ed.my.salesforce.com
        - run: | 
              echo ${{ secrets.DEV_HUB_URL }}
              echo $DEV_HUB_URL
              echo $DEV_HUB_URL > devHubURLFile
              sfdx force:auth:sfdxurl:store -d -f devHubURLFile
              rm devHubURLFile
              chmod +x ./scripts/createScratchOrg.sh
              ./scripts/createScratchOrg.sh
