

name:  deployToScratchOrg
# Controls when the workflow will run

on:
  # Triggers the workflow on pull request events but only for the main branch
  workflow_dispatch:
  
  pull_request:
    branches: 
      - main
      - 'feature/*'
      - 'bugfix/*'
      
env:
  DEV_HUB_URL: "force://PlatformCLI::5Aep861mdLLi91HqFcAEF7Il08vCce3_hZWIrFrRAg1XOoKDgDGm5h1fU.nfWL9oAX5qvk5jsKFdhK0IkYCehSV@deloitte-2f2-dev-ed.my.salesforce.com"

  # Allows you to run this workflow manually from the Actions tab

# A workflow run is made up of one or more jobs that can run sequentially or in parallel

jobs:
  deploy-org:
    runs-on: ubuntu-latest
    container : salesforce/salesforcedx:latest-full
    defaults:
      run:
        shell: bash
    steps:
        - uses: actions/checkout@v2
        - run: | 
              echo force://PlatformCLI::5Aep861mdLLi91HqFcAEF7Il08vCce3_hZWIrFrRAg1XOoKDgDGm5h1fU.nfWL9oAX5qvk5jsKFdhK0IkYCehSV@deloitte-2f2-dev-ed.my.salesforce.com > devHubURLFile
              sfdx force:auth:sfdxurl:store -d -f devHubURLFile
              rm devHubURLFile
              echo 1
              echo $pwd
              echo 2
              chmod +x ./scripts/config.sh
              chmod +x ./scripts/CreateScratchOrg.sh
              ./scripts/CreateScratchOrg.sh
      
       
       
